### ISSUE TITLE
Rultor says it doesn't understand commands

### ISSUE THREAD

**Issue by krzyk** [yegor256/rultor#980] opened 2016-01-10 11:11 UTC
If commander issues a rultor command, rultor replies with: 
> I'm sorry, I don't understand you :( Check this page and try again please

but it performs the command (by asking architect for confirmation).

Rultor shouldn't complain about wrong command if the command is correctly asked by a commander.

**Comment by yegor256** [comment] 2016-01-11 10:39
@krzyk duplicate of #979

**Closed by yegor256** 2016-01-11 10:39 UTC
