### ISSUE TITLE
Can I use `main` branch instead of `master` branch?

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1571] opened 2023-01-30 15:08 UTC
I'm trying to merge changes by rultor in that [PR](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44#issuecomment-1408753022).
Here is my `.rultor.yaml` file:
```yaml
architect:
  - lombrozo
docker:
  image: yegor256/rultor-image:1.13.0
merge:
  script: mvn clean install -Pqulice --errors --batch-mode
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean install -Pqulice --errors --batch-mode
```

**Expected behaviour:** Rultor merges changes successfully.
**Actual behaviour**: I get the next [exception](https://www.rultor.com/t/29908-1408750651):
```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 4099449
+ echo '2.0-SNAPSHOT BUILD'
2.0-SNAPSHOT BUILD
+ date
Mon 30 Jan 2023 03:47:49 PM CET
+ uptime
 15:47:49 up 67 days, 21:25,  0 users,  load average: 0.00, 0.00, 0.00
+ cat
com.rultor.spi.Profile: There is no 'merge' section in .rultor.yml
	at com.rultor.agents.req.StartsRequest.docker(StartsRequest.java:350)
	at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:255)
	at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:148)
	at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler.lambda./run.sh(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)

+ exit -1
'cid' file is absent, most probably the Docker container wasn't started correctly
```

I suppose, the reason in my `main` branch. I don't use `master` branch at all. Could it be a reason of the problem?

**Comment by volodya-lombrozo** [comment] 2023-01-30 15:08
@yegor256

**Comment by yegor256** [comment] 2023-01-30 15:11
Duplicate of #1302

**Closed by yegor256** 2023-01-30 15:11 UTC
