### ISSUE TITLE
build fails on Win7 with Cannot run program "/bin/bash"

### ISSUE THREAD

**Issue by wentwog** [yegor256/rultor#708] opened 2015-01-04 17:33 UTC
```
Tests run: 8, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 7.057 sec <<< FAILURE! - in com.rultor.agents.req.StartsRequestTest
startsReleaseRequest(com.rultor.agents.req.StartsRequestTest)  Time elapsed: 0.255 sec  <<< ERROR!
java.lang.IllegalStateException: java.io.IOException: Cannot run program "/bin/bash" (in directory "C:\Users\artem\AppData\Local\Temp\junit5014121005724063031\junit731223
8384425855268"): CreateProcess error=2, Не удается найти указанный файл
        at com.jcabi.log.VerboseProcess.start(VerboseProcess.java:193)
        at com.jcabi.log.VerboseProcess.<init>(VerboseProcess.java:106)
        at com.rultor.agents.req.StartsRequestTest.repo(StartsRequestTest.java:439)
        at com.rultor.agents.req.StartsRequestTest.startsReleaseRequest(StartsRequestTest.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/bin/bash" (in directory "C:\Users\artem\AppData\Local\Temp\junit5014121005724063031\junit7312238384425855268"): Creat
eProcess error=2
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.jcabi.log.VerboseProcess.start(VerboseProcess.java:189)
        ... 23 more
Caused by: java.io.IOException: CreateProcess error=2
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more
```

**Comment by yegor256** [comment] 2015-01-04 18:48
@wentwog looks like a duplicate of https://github.com/yegor256/rultor/issues/686

**Closed by yegor256** 2015-01-04 18:48 UTC
