### ISSUE TITLE
Rultor responds to 'merge' command twise

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#979] opened 2016-01-08 20:01 UTC
![screenshot from 2016-01-08 22 01 21](https://cloud.githubusercontent.com/assets/1388994/12208121/646fe1a4-b653-11e5-917b-3e23d91ae89f.png)

**Comment by yegor256** [comment] 2016-01-08 22:13
@longtimeago duplicate of #976

**Closed by yegor256** 2016-01-08 22:13 UTC

**Comment by longtimeago** [comment] 2016-01-08 22:18
@yegor256 oops, sorry
