### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by jeromebridge** [yegor256/rultor#924] opened 2015-08-22 15:21 UTC
When I do a <a href="http://www.rultor.com/t/4908-133713632">release</a> the build appears to be successful but I get an error at the end `No space left on device` at the very end.  Here is my config if it helps:
````
install: |-
  sudo apt-get -q -y install lib32z1 lib32ncurses5 lib32bz2-1.0
release:
  pre: false
  artifacts:
    - "inspro-fitnesse-installer/dist/inspro-fitnesse-installer-${tag}.exe"
  script: |
    mvn versions:set "-DnewVersion=${tag}" -DartifactId=* -DgroupId=* -DoldVersion=*
    git commit -am "${tag}"
    mvn clean deploy --settings documentation/files/maven-settings.xml -Prelease
````

**Comment by yegor256** [comment] 2015-08-22 15:50
@jeromebridge now it should work, I cleaned some space on the server. But the problem is bigger, we have to remove unnecessary docker images from the server. Let's keep this ticket open until I create a proper fix

**Comment by jeromebridge** [comment] 2015-08-22 16:21
@yegor256 Thanks for the quick response.  My release was able to complete.

**Comment by yegor256** [comment] 2015-08-23 20:57
@rultor release, tag is `1.57`

**Comment by yegor256** [comment] 2015-08-23 20:59
@jeromebridge I believe it's fixed now, the right way. please close the ticket.

**Comment by yegor256** [comment] 2015-09-10 14:04
@jeromebridge could you please close this ticket?

**Closed** 2015-09-11 21:46 UTC
