### ISSUE TITLE
Incorrect mvn versions:set parameters when invoking Release command

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/rultor#883] opened 2015-06-29 01:05 UTC
In one of our projects (https://github.com/teamed/xockets-layer/issues/356) I was trying to release a new version. It failed, because the build was unable to find a version-specific arfifact (see [log](http://www.rultor.com/t/4318-115554594)):
```
[INFO] --- exec-maven-plugin:1.3.2:exec (default) @ xockets-layer --- JAR file target/xockets-layer-0.4-jar-with-dependencies.jar is absent
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:58 min
[INFO] Finished at: 2015-06-26T07:14:48+00:00
[INFO] Final Memory: 58M/467M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project xockets-layer: Command execution failed. Process exited with an error: 255 (Exit value: 255) -> [Help 1]
```

It turns out, Rultor was invoking the `mvn versions:set` command incorrectly. It's supposed to be `mvn versions:set -DnewVersion=0.4`, but we got the following:

```
+ sudo gem install --no-ri --no-rdoc est
Successfully installed est-0.3 1
gem installed
+ mvn versions:set '-DnewVersion='\''0.4'\'''
[INFO] Scanning for projects...
```

This did not occur in our previous release [see log](http://www.rultor.com/t/4101-110215713):

```
+ sudo gem install --no-ri --no-rdoc est
Successfully installed est-0.3 1 gem installed
+ mvn versions:set -DnewVersion=0.3
[INFO] Scanning for projects...
```

Let's investigate and fix.

**Comment by yegor256** [comment] 2015-06-29 01:39
@carlosmiranda it's a duplicate of https://github.com/yegor256/rultor/issues/882

**Closed by yegor256** 2015-06-29 01:39 UTC

**Comment by carlosmiranda** [comment] 2015-06-29 01:47
@yegor256 Right, thanks. Didn't notice it.
