### ISSUE TITLE
Rultor suffers from "pipe2: too many open files"

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#783] opened 2015-02-23 14:39 UTC
http://www.rultor.com/t/2067-75549656

msg="Error response from daemon: Cannot start container 0149bb4c564b666566de35bf6ee6432422457d428a10d2605c2ff42466f20efb: pipe2: too many open files"

Looks like we hit some limit

**Comment by longtimeago** [comment] 2015-02-23 14:42
here is the discussion and possible fix
https://github.com/docker/docker/issues/1044

**Comment by yegor256** [comment] 2015-03-01 03:37
@longtimeago we don't have 118+ containers on the server. I think it's a temporary problem with the server itself and it can't be fixed inside rultor. if the server is under heavy load, rultor/docker may ocasionally have

**Closed** 2015-03-01 03:37 UTC

**Comment by longtimeago** [comment] 2015-03-01 08:11
@yegor256 got it. Thanks

**Comment by longtimeago** [comment] 2015-03-01 08:23
@yegor256 something new
Status: Image is up to date for yegor256/rultor:latest ++ pwd ++ pwd + docker run --rm -v /tmp/rultor-Wt8W:/main '--env=MAVEN_OPTS=-XX:MaxPermSize=256m -Xmx1g' --env=fork=git@github.com:krzyk/xockets-hadoop-transport.git --env=fork_branch=489 --env=head=git@github.com:teamed/xockets-hadoop-transport.git --env=head_branch=master --memory=4g --cidfile=/tmp/rultor-Wt8W/cid -w=/main --name=teamed_xockets-hadoop-transport_494 yegor256/rultor /main/entry.sh time="2015-03-01T09:15:50+01:00" level="fatal" msg="Post http:///var/run/docker.sock/v1.16/containers/d644c9ae269ebcb14f8618fbe40200db2feac7cc90efc7060cc8421653dec977/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?"

**Comment by yegor256** [comment] 2015-03-01 20:11
let's move the discussion to #792 the root cause of the problem is explained there
