### ISSUE TITLE
bug on firefox

### ISSUE THREAD

**Issue by caarlos0** [yegor256/rultor#777] opened 2015-02-17 03:06 UTC
Acessing rultor.com on firefox is a little "buggy":

![screenshot 2015-02-17 01 04 58](https://cloud.githubusercontent.com/assets/245435/6222765/3001a67c-b641-11e4-9e16-8f184f4ae321.png)

The graph looks messed up.

**Comment by yegor256** [comment] 2015-02-17 04:54
it's a duplicate of #562

**Closed by yegor256** 2015-02-17 04:54 UTC
