### ISSUE TITLE
Attach Binaries To Release Not Working

### ISSUE THREAD

**Issue by jeromebridge** [yegor256/rultor#925] opened 2015-08-24 15:46 UTC
This doesn't seem to be working for me.  Here is the configuration I'm using:
````
install: |-
  sudo apt-get -q -y install lib32z1 lib32ncurses5 lib32bz2-1.0
release:
  pre: false
  artifacts:
    - "inspro-fitnesse-installer/dist/inspro-fitnesse-installer-${tag}.exe"
  script: |
    mvn versions:set "-DnewVersion=${tag}" -DartifactId=* -DgroupId=* -DoldVersion=*
    git commit -am "${tag}"
    mvn clean deploy --settings documentation/files/maven-settings.xml -Prelease
````
Here is what Rultor says it knows:
````
<?xml version="1.0" encoding="UTF-8"?>
<p>
   <entry key="install">sudo apt-get -q -y install lib32z1 lib32ncurses5 lib32bz2-1.0</entry>
   <entry key="release">
      <entry key="pre">false</entry>
      <entry key="artifacts">
         <item>inspro-fitnesse-installer/dist/inspro-fitnesse-installer-${tag}.exe</item>
      </entry>
      <entry key="script">mvn versions:set "-DnewVersion=${tag}" -DartifactId=* -DgroupId=* -DoldVersion=*
git commit -am "${tag}"
mvn clean deploy --settings documentation/files/maven-settings.xml -Prelease</entry>
   </entry>
</p>
````
Here is my <a href="http://www.rultor.com/t/4908-133718025">log output</a> at the end of the release:
````
+ mv /home/r/repo . 
++ whoami 
+ chown -R root repo 
+ '[' -n '' ']' 
++ whoami 
+ sudo chown -R rultor repo 
+ cd repo 
+ git checkout __rultor Already on '__rultor' 
+ git tag 1.00.019 -m '1.00.019: tagged by rultor.com' 
+ git reset --hard HEAD is now at 2b17609 1.00.019 
+ git clean -fd 
+ git checkout master Switched to branch 'master' 
+ git branch -D __rultor Deleted branch __rultor (was 2b17609). 
+ git push --all origin Everything up-to-date 
+ git push --tags origin To git@github.com:jeromebridge/inspro-integration.git * [new tag]	1.00.019 -> 1.00.019
````

**Comment by alex-palevsky** [comment] 2015-08-27 17:12
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment] 2015-09-13 10:28
@jeromebridge it's a duplicate of #832

**Closed by yegor256** 2015-09-13 10:28 UTC
