### ISSUE TITLE
Rultor sometimes fails to use the newly downloaded Docker image

### ISSUE THREAD

**Issue by Suseika** [yegor256/rultor#942] opened 2015-10-07 04:12 UTC
When you setup a custom Docker image in your `.rultor.yml`, rultor is going to download it. Often it results in this weird log. 

See the last two lines: it says that it downloaded the new image, and then it immediately says that there is no such image. 

I get this error probably once every couple of weeks when I'm working with a repo that has a custom Docker image for Rultor:

https://github.com/Suseika/inflectible/pull/204#issuecomment-146070840

```
9926216677d0: Download complete
9926216677d0: Download complete
Status: Downloaded newer image for docker.io/maven:3.2.5-jdk-8
+ docker ps --filter=status=exited
+ grep --quiet '\sSuseika_inflectible_204\s*$'
++ pwd
++ pwd
+ docker run --rm -v /tmp/rultor-mUaP:/main --env=fork=git@github.com:Suseika/inflectible.git --env=fork_branch=203 --env=head=git@github.com:Suseika/inflectible.git --env=head_branch=master --env=pull_id=204 '--env=pull_title=Rewrite Hamcrest matcher for better code quality' --privileged=true --hostname=docker --memory=6g --cidfile=/tmp/rultor-mUaP/cid -w=/main --name=Suseika_inflectible_204 maven:3.2.5-jdk-8 /main/entry.sh
Unable to find image 'maven:3.2.5-jdk-8' locally
Trying to pull repository docker.io/maven ...
9926216677d0: Pulling image (3.2.5-jdk-8) from docker.io/maven
9926216677d0: Pulling image (3.2.5-jdk-8) from docker.io/maven, endpoint: https://registry-1.docker.io/v1/
9926216677d0: Pulling dependent layers
511136ea3c5a: Download complete
7f8e41a4d968: Pulling metadata
7f8e41a4d968: Pulling fs layer
7f8e41a4d968: Download complete
3503509cb35e: Pulling metadata
3503509cb35e: Pulling fs layer
3503509cb35e: Download complete
f2f938f89746: Pulling metadata
f2f938f89746: Pulling fs layer
f2f938f89746: Download complete
cac3e7468682: Pulling metadata
cac3e7468682: Pulling fs layer
cac3e7468682: Download complete
673ed3b40c5f: Pulling metadata
673ed3b40c5f: Pulling fs layer
673ed3b40c5f: Download complete
98ae4450a0d5: Pulling metadata
98ae4450a0d5: Pulling fs layer
98ae4450a0d5: Download complete
841d7029ca0d: Pulling metadata
841d7029ca0d: Pulling fs layer
841d7029ca0d: Download complete
9af9b1423411: Pulling metadata
9af9b1423411: Pulling fs layer
9af9b1423411: Download complete
60b04d8f21c9: Pulling metadata
60b04d8f21c9: Pulling fs layer
60b04d8f21c9: Download complete
6e80a5e7f4c2: Pulling metadata
6e80a5e7f4c2: Pulling fs layer
6e80a5e7f4c2: Download complete
58e2e1eb4d9f: Pulling metadata
58e2e1eb4d9f: Pulling fs layer
58e2e1eb4d9f: Download complete
e97b1f2bcbf6: Pulling metadata
e97b1f2bcbf6: Pulling fs layer
e97b1f2bcbf6: Download complete
586af018e3d6: Pulling metadata
586af018e3d6: Pulling fs layer
586af018e3d6: Download complete
9926216677d0: Pulling metadata
9926216677d0: Pulling fs layer
9926216677d0: Download complete
9926216677d0: Download complete
Status: Downloaded newer image for docker.io/maven:3.2.5-jdk-8
time="2015-10-07T03:50:20Z" level="fatal" msg="Error response from daemon: No such image: maven:3.2.5-jdk-8 (tag: 3.2.5-jdk-8)" 
```

**Comment by yegor256** [comment] 2015-10-07 22:51
@Suseika hm.. this smells like a bug, caused by this change: 8083b9620457463b225fc07576b4c3dc61492ccc

**Comment by yegor256** [comment] 2015-10-07 22:52
@Suseika in a nutshell, we delete too old images (over than a month) from the server, in order to save space. Maybe (I'm guessing) this deletion is happening first, than you start a build, the image is downloaded and then rultor (in another process) immediately deletes it again. Sort of concurrency issue.

**Comment by yegor256** [comment] 2015-10-07 23:03
@Suseika this may be related: https://github.com/docker/docker/issues/10708

**Comment by yegor256** [comment] 2015-10-07 23:32
@rultor release, tag is `1.57.6`

**Comment by yegor256** [comment] 2015-10-08 02:35
@rultor release, tag is `1.57.6`

**Comment by sils1297** [comment] 2015-10-09 05:40
@yegor256 we're also experiencing this (and it's blocking our workflow). See https://github.com/coala-analyzer/coala/pull/943

**Comment by yegor256** [comment] 2015-10-09 06:29
@sils1297 are you seeing it every single build cycle or occasionally?

**Comment by sils1297** [comment] 2015-10-09 06:33
as you can see in the PR it appeared 3 times in a row now

**Comment by sils1297** [comment] 2015-10-10 08:05
@yegor256 any news or possible workaround? Rultor remains unusable for us and we rely on it for our workflow.

**Comment by yegor256** [comment] 2015-10-11 02:22
@Suseika @sils1297 I confirm that there is a problem with Docker. I'm doing this manually on the server:

```
$ docker pull coala/rultor-python
```

It downloads images, but then there is no image... I'm trying to understand what's going on

**Comment by yegor256** [comment] 2015-10-11 02:27
@rultor release, tag is `1.57.7`

**Comment by yegor256** [comment] 2015-10-11 04:58
@Suseika @sils1297 try now please, should be fine

**Comment by sils1297** [comment] 2015-10-11 09:42
@yegor256 after the occasional [network error I already know from rultor](http://www.rultor.com/t/5397-147174176) the merge worked with your workaround applied.

**Comment by alex-palevsky** [comment] 2015-10-14 18:07
@suseika I will find a developer for the task soon...

**Comment by alex-palevsky** [comment] 2015-10-14 18:08
@suseika I set milestone here to `2.0`, let me know if it is wrong

**Comment by alex-palevsky** [comment] 2015-10-14 18:10
@suseika thanks for tis bug, I topped your account for 15 mins, transaction `AP-99A41156V2653612L`

**Comment by alex-palevsky** [comment] 2016-01-24 15:05
@gumbelmj this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by gumbelmj** [comment] 2016-01-29 12:48
@alex-palevsky Is there a design document for Rultor somewhere?  I'm having trouble even finding where a new Docker image is pulled down.

**Comment by alex-palevsky** [comment] 2016-01-31 12:15
> @alex-palevsky Is there a design document for Rultor somewhere?  I'm having trouble even finding where a new Docker image is pulled down.

@gumbelmj everything is in README.md, that's the only place for documentation

**Comment by alex-palevsky** [comment] 2016-02-08 15:53
@gumbelmj the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, at the moment it is: [-60](http://www.netbout.com/b/36306?open=rating)

**Comment by sils1297** [comment] 2016-02-11 20:13
FWIW we're getting this

```
Post http:///var/run/docker.sock/v1.20/images/create?fromImage=coala%2Frultor-python%3Alatest: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
'cid' file is absent, container wasn't started correctly
```

error a lot which seems to be related to this issue. It's really getting annoying. :/

**Comment by reiz** [comment] 2016-02-12 17:50
I have the same issue on some Kubernetes Minions! Any workaround?

**Comment by yegor256** [comment] 2016-02-12 19:36
@sils1297 this happens when docker deamon is down. This may happen right after the server is rebooted. Can you please submit a separate ticket about this, I'll try to fix it right.

**Comment by alex-palevsky** [comment] 2016-02-14 13:16
@gumbelmj it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, current score is: [-90](http://www.netbout.com/b/36306?open=rating)

**Comment by alex-palevsky** [comment] 2016-02-21 17:54
@guiandmag could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by original-brownbear** [comment] 2016-02-28 12:30
@guiandmag how's it going with this? Are you working/planning to work on this issue? 
It's been 7 days since you were assigned to it and an issue of some importance and stuck for some time now as you can see.
I don't think it would benefit anyone if this timed out needlessly again.

**Comment by original-brownbear** [comment] 2016-03-02 13:54
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment] 2016-03-02 16:05
> @alex-palevsky assign me please.

@original-brownbear sure, the ticket is yours, go ahead

**Comment by original-brownbear** [comment] 2016-03-03 17:19
@Suseika am I right to assume that this is not happening anymore for you with the workaround turning off image deleting applied in here 7c874cb7cd06360fcab58c8c23ecff4e27657676 back in October?
If so could you please close this ? :)

We can simply continue with #906 then and handle the disk space issue from not deleting images there.

**Closed** 2016-03-03 17:41 UTC
Labels: 30 mins, @original-brownbear, bug, DEV

**Comment by alex-palevsky** [comment] 2016-03-04 19:52
@original-brownbear Thanks for your contribution, **45 mins** was added to your account, payment ID is `AP-1DK486132C746364R`, 26 hours and 55 mins spent total. m=1615, that's why a bonus here for fast delivery. added +45 to your rating, now it is equal to [+619](http://www.netbout.com/b/36646?open=rating)
