### ISSUE TITLE
How to start rultor to run/use .rultor.xml from some project

### ISSUE THREAD

**Issue by pecko** [yegor256/rultor#941] opened 2015-09-29 15:53 UTC
I would like to start rultor locally and build the jcabi-github project.
I have tried the following:

```
sudo docker run -i -t yegor256/rultor /bin/bash
git clone ...
cd jcabi-github
mvn clean install -qulice
```

However, this build doesn't run integration tests as remote rultor do it.
How to can I tell rultor to run script defined in .rultor.xml when running rultor locally?

See https://github.com/jcabi/jcabi-github/issues/1170

**Comment by yegor256** [comment] 2015-09-29 16:02
@pecko it's a duplicate of #549

**Closed by yegor256** 2015-09-29 16:02 UTC
