### ISSUE TITLE
Rultor fails to create script.sh with particular character in script

### ISSUE THREAD

**Issue by tannakartikey** [yegor256/rultor#1193] opened 2017-07-03 11:06 UTC
I have used the command `Xvfb :99 &` in my `.rultor.yml` to send the process in the background.
This is the error I am getting because of it:
 ```/home/r/script.sh: line 9: syntax error near unexpected token `;'```
Build log: http://www.rultor.com/t/12220-312615627

Rultor converts the command to `Xvfb :99 &amp;` while parsing YAML to XML which should be the reason of the failure.

**Comment by 0crat** [comment] 2017-07-03 11:06
@yegor256 please, pay attention to this issue

**Comment by tannakartikey** [comment] 2017-07-03 14:31
@yegor256  I have identified the problem.The command `Xvfb :99 &` was causing the failure.

**Comment by yegor256** [comment] 2017-07-03 14:46
@tannakartikey yes, please, change the title and the description

**Comment by 0crat** [comment] 2017-11-01 08:53
Job `gh:yegor256/rultor#1193` is in scope.

**Comment by 0crat** [comment] 2017-11-16 20:07
Job `gh:yegor256/rultor#1193` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-11-21 20:00
@filfreire this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment] 2017-11-24 20:19
@filfreire this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment] 2017-11-26 20:01
@filfreire resigned from `gh:yegor256/rultor#1193`, please stop working.

**Comment by 0crat** [comment] 2017-11-26 21:22
Job `gh:yegor256/rultor#1193` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-12-06 23:28
Oops! Job `gh:yegor256/rultor#1193` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-12-06 23:28
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2017-12-06 23:28
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2017-12-06 23:28
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment] 2017-12-07 13:48
Job `gh:yegor256/rultor#1193` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by paulodamaso** [comment] 2019-01-02 13:39
@rultor status

**Comment by paulodamaso** [comment] 2019-01-02 13:52
@0crat status

**Comment by 0crat** [comment] 2019-01-02 13:52
> @0crat status ([here](https://github.com/yegor256/rultor/issues/1193#issuecomment-450868301))

@paulodamaso This is what I know about this job in [C3SAYRPH9](https://www.0crat.com/p/C3SAYRPH9), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1193](https://github.com/yegor256/rultor/issues/1193) is [in scope](http://www.zerocracy.com/policy.html#14) for 14mon
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @tannakartikey[/z](https://www.0crat.com/u/tannakartikey): This user reported the ticket
    * @filfreire[/z](https://www.0crat.com/u/filfreire): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3SAYRPH9?q=%7Bjob%3A%27gh%3Ayegor256%2Frultor%231193%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment] 2019-01-02 14:38
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment] 2019-01-05 03:12
@0crat wait for https://github.com/yegor256/rultor/pull/1286 review

**Comment by 0crat** [comment] 2019-01-05 03:13
> @0crat wait for https://github.com/yegor256/rultor/pull/1286 review ([here](https://github.com/yegor256/rultor/issues/1193#issuecomment-451623068))

@paulodamaso The impediment for [#1193](https://github.com/yegor256/rultor/issues/1193) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-02-06 03:38
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-02-11 04:40
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-02-16 05:41
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-02-21 06:39
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-02-26 07:39
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-03-03 08:44
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-03-08 10:26
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-03-13 10:54
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-03-18 11:39
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-03-23 12:41
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by Glusk2** [comment] 2019-10-20 01:32
The problem is that rultor uses an XML-based data store and has to escape `&`s. For variety, here are the other special characters that [Xembly](https://github.com/yegor256/xembly/) escapes:

https://github.com/yegor256/xembly/blob/aea87929c79d4e968a43b4372fc345a4c051669e/src/main/java/org/xembly/Arg.java#L121

**Comment by 0crat** [comment] 2019-10-21 08:45
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-10-26 09:28
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-10-31 09:59
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-05 10:44
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-10 11:46
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-15 12:46
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-20 14:35
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-25 14:43
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-11-30 15:52
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-12-05 16:53
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2019-12-10 19:18
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#1193](https://github.com/yegor256/rultor/issues/1193); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment] 2022-11-07 08:25
@tannakartikey I believe it's fixed

**Closed by yegor256** 2022-11-07 08:25 UTC
Labels: bug, help wanted

**Comment by 0crat** [comment] 2022-11-07 08:47
Job `gh:yegor256/rultor#1193` is not assigned, can't get performer
