### ISSUE TITLE
Command/Output Ordering is messed up nondeterministically

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#901] opened 2015-07-17 12:59 UTC
See http://www.rultor.com/t/4530-122266254 the lines after `+ bash .misc/deploy.rultor.sh`, first it echoes two ls commands, then it shows the output of the two ls commands and then it does the third command and its output.

So some ordering problem seems to be there.

**Comment by yegor256** [comment] 2015-07-17 17:59
@sils1297 I can't find the content of `.misc/deploy.rultor.sh` in your repo, but I can only suspect that you have something like this there:

```
ls -la & ls -al
```

Am I right?

**Comment by sils1297** [comment] 2015-07-17 18:01
@yegor256 nope. It was

```
ls -la .
ls -la ..
ls -la .misc
```

**Comment by yegor256** [comment] 2015-07-17 18:03
@sils1297 it's just technically not possible... can you show full code of your script?

**Comment by sils1297** [comment] 2015-07-17 18:04
@yegor256 just pushed it for you:

https://github.com/sils1297/coala/blob/sils/rultor/.misc/deploy.rultor.sh

as you can see from the commit sha it's the very same commit used in the log.

**Comment by yegor256** [comment] 2015-07-17 18:37
@sils1297 I can't reproduce the problem... What do you have in `.rultor.yml`?

**Comment by sils1297** [comment] 2015-07-17 19:11
@yegor256 this branch points to the very same commit that resultet in the failure, here's the branch link:

https://github.com/sils1297/coala/tree/sils/rultor

thats the rultor.yml then: https://github.com/sils1297/coala/blob/sils/rultor/.rultor.yml

**Comment by alex-palevsky** [comment] 2015-09-27 13:39
@sils1297 we will find someone to do this task, soon

**Comment by alex-palevsky** [comment] 2015-09-27 13:40
@sils1297 since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment] 2016-02-22 19:13
@yegor256 since you asked, this is a result of output buffering occurring, since the containers are not ran in line buffered mode.
=> Output is dumped in 4096byte chunks.

Likely this can simply be fixed by running the container with the -t ( tty => line buffering) flag, but this needs to be investigated. Could be we have multiple spots where buffering can occur in the execution.

Pushed a small demo of this here: https://github.com/original-brownbear/output-buffering-docker
This should make it trivial to understand the issue for whoever deals with this.

**Comment by yegor256** [comment] 2016-02-22 22:34
@original-brownbear interesting catch! well, let's try the `-t` flag?

**Comment by original-brownbear** [comment] 2016-02-22 22:41
@yegor256 yes, lets go for it :)

**Comment by original-brownbear** [comment] 2016-02-23 12:43
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment] 2016-02-23 17:15
> @alex-palevsky assign me please.

@original-brownbear yep, it is yours, go ahead

**Comment by original-brownbear** [comment] 2016-02-24 02:43
@yegor256 could you run the deploy on this one (#1023) ? :) , #982 still prevents me from doing that.

**Comment by yegor256** [comment] 2016-02-24 05:03
@rultor deploy

**Comment by original-brownbear** [comment] 2016-02-24 10:50
@sils1297 can you try again ? This issue should be resolved now :)

**Comment by sils1297** [comment] 2016-02-24 10:53
Hey, I don't have time to try it out, sorry.

**Comment by original-brownbear** [comment] 2016-02-24 11:00
@sils1297 no problem :), maybe you could still close this given #1023 has been merged and I think clearly lays out ( and has a screenshot :) ) how and why this fixes this issue ?

**Closed** 2016-02-24 11:04 UTC
Labels: 30 mins, @original-brownbear, bug, DEV

**Comment by alex-palevsky** [comment] 2016-02-25 17:53
@original-brownbear **45 mins** sent to your balance (ID `AP-1YD48006MS2809915`), many thanks! It took 24 hours and 22 mins.; there is a bonus for fast delivery (m=1462); +45 added to your rating, current score is: [+208](http://www.netbout.com/b/36646?open=rating)
