### ISSUE TITLE
Rultor sends comments delayed

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#937] opened 2015-09-25 19:25 UTC
See https://github.com/python-babel/babel/pull/245#issuecomment-143330658 , no additional comments because I don't know what's going on there except that this occurred several times for me now, that rultor showed me the "I don't understand you" message  about some comment that was done a long time ago when requesting a merge from rultor.

**Comment by yegor256** [comment] 2015-09-25 20:39
@sils1297 not sure I understand the problem... looks like a normal communication flow in that ticket you referred... what exactly is wrong?

**Comment by sils1297** [comment] 2015-09-26 18:08
@yegor256 look closely at the order of comments:

4 days ago I did a comment with

    `@rultor merge`

in it. This shouldn't trigger rultor because of backticks, I presume.

A few days later I did the `@rultor merge` comment and the first response to it is actually a response to the comment 4 days ago:

> > @etanol @erickwilder whoever comes first, could you please self assign and review this? If you're...
> 
> @sils1297 I see you're talking about me, but I don't understand it. If you want to say something to me directly, start a message with @rultor 

so this comment shouldn't be there at all, right?

**Comment by yegor256** [comment] 2015-09-26 21:06
@sils1297 this is by design and we can't fix it anyhow. When you put "rultor" into backticks, Github doesn't notify our engine about it. We simply don't pay attention to this ticket. Later, when you actually refer to rultor and the ticket catches our attention, we go through **all** messages unseen before. When we find the one where "rultor" is mentioned (even though inside backticks), we reply to you.

**Comment by sils1297** [comment] 2015-09-26 21:15
Why don't you filter out backtick usages? I would only use rultor in
backticks when explaining it to someone and then I wouldn't want rultor to
pick that up.

**Comment by yegor256** [comment] 2015-09-26 21:22
@sils1297 we can't... We don't know where backticks starts and where they end. We need to do a proper Markdown rendering in order to understand that. And this would be totally out of scope of the project... I believe

**Comment by sils1297** [comment] 2015-09-26 21:42
Well, there are libraries for that.

So one could also look for a simpler method of recognizing relevant
comments, e.g. requiring the user to address rultor at the first part of a
sentence/line. If this is not given, don't answer at all.

This'll solve the delayed answers (which don't hold anything useful in any
case, right?), as well as the annoying fact that rultor responds if someone
answers to any rultor related comment via email while not taking anything
useful away.

**Comment by yegor256** [comment] 2015-09-26 21:47
@sils1297 well, yes, but we intentionally created this feature in #683 (you can see our discussion there, to understand the reason). Completely removing it would not be a good idea now. Rendering the entire message into HTML just in order to avoid that situations... isn't it an overkill?

**Comment by sils1297** [comment] 2015-09-26 22:27
> @sils1297 well, yes, but we intentionally created this feature in #683
(you can see our discussion there, to understand the reason). Completely
removing it would not be a good idea now.

I'm not taking about completely removing it. I'm speaking about reducing
the "I didn't understand you" messages, only show them when rultor was
mentioned in the beginning of the line and mentioning in the documentation
that rultor needs to be mentioned there.

This would greatly help my and others mailboxes. (And I probably don't have
to tell you guys about the pressure a developers mailbox has to withstand
;))

> Rendering the entire message into HTML just in order to avoid that
situations... isn't it an overkill?

Well HTML is totally unrelated, we wouldn't want to transfer the parsing
complexity from markdown to html, right?

**Comment by yegor256** [comment] 2015-09-27 00:50
@sils1297 the reason why we check the entire message is that people very often don't understand how rultor works. They don't start their messages with the right prefix and they get no response. That's why this feature was introduced in #683 In other words, most of the users are juniors, that's why we need to focus on them. More advanced users (like yourself) can handle these situations and avoid problems. It's a minor problem, actually. Just ignore the message and move on :)

**Closed by yegor256** 2015-09-27 00:50 UTC
